<a href="https://colab.research.google.com/github/Pradeep24032004/PyTorch-/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvdia-smi


/bin/bash: line 1: nvdia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [ ]:
#Introduction to tensors
#creating tensors
#scalars
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX


tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([3, 4])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

Generally in tensors scalars are represented by lower case letters like 'a', vectors are represented by lower case letters like 'y', matrix is represented by upper case letters like 'Q' and tenosrs are represented by upper case letters like 'X'

In [ ]:
#Random Tensors
#random tensors are important because the way many neural networks learn is that they start with tensors full random numbers and then adjust the random numbers to better represent the data
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8006, 0.7697, 0.5569, 0.2465],
        [0.0328, 0.5557, 0.7326, 0.7765],
        [0.4748, 0.9311, 0.5612, 0.8955]])

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels(R, G, B)
random_image_tensor

tensor([[[0.3724, 0.8430, 0.8292],
         [0.5683, 0.2667, 0.7196],
         [0.4645, 0.3085, 0.7044],
         ...,
         [0.1470, 0.9230, 0.6880],
         [0.5125, 0.2662, 0.2900],
         [0.6446, 0.3978, 0.6927]],

        [[0.4587, 0.0367, 0.9382],
         [0.8606, 0.1024, 0.1851],
         [0.1515, 0.8189, 0.2133],
         ...,
         [0.3912, 0.5463, 0.5551],
         [0.2635, 0.6979, 0.7533],
         [0.0675, 0.2139, 0.9902]],

        [[0.1669, 0.8991, 0.2256],
         [0.3666, 0.7659, 0.3456],
         [0.3750, 0.8360, 0.9508],
         ...,
         [0.6783, 0.2311, 0.1425],
         [0.0947, 0.7229, 0.0422],
         [0.2886, 0.5955, 0.3480]],

        ...,

        [[0.4374, 0.1912, 0.5600],
         [0.0446, 0.8805, 0.2974],
         [0.2969, 0.4474, 0.7895],
         ...,
         [0.4585, 0.2583, 0.4704],
         [0.9329, 0.3593, 0.3067],
         [0.7583, 0.2178, 0.1960]],

        [[0.8995, 0.7350, 0.3348],
         [0.0744, 0.7123, 0.8582],
         [0.

In [ ]:
random_image_tensor.ndim

3

***Zeros and Ones***

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#creat6e tensor of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#data type
ones.dtype

torch.float32

Creating a range of tensors and tensors-like


In [ ]:
#use torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_ten = torch.arange(start=1, end = 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tenors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Tensor datatypes
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 4.0, 7.0], dtype=None,#datatype whether float or int
                               device=None,  #running on which device cpu or gpu
                               requires_grad=False ) #to keep track of gradient descent or not
float_32_tensor

tensor([3., 4., 7.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 4., 7.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 16., 49.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

**Getting information from tensors(tensor attributes)**
1. tenosr.dtype -gives info about data rype of tensor
2. tensor.shape - gives the shape of the tensor
3. tensor.device - gives info about on which device the code is running(cpu or gpu etc)

In [ ]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Dtatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1679, 0.8282, 0.2183, 0.2290],
        [0.3181, 0.0833, 0.9110, 0.8568],
        [0.5930, 0.5144, 0.7196, 0.0595]])
Dtatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
#Manipulating tensors(Tensor operations)
#create a tensor and 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10 #can also write as torch.add(torch, 10)

tensor([11, 12, 13])

In [ ]:
#multiply tensor by 10
tensor * 10
print(tensor)
#reasigning tensor
tensor = tensor * 10 #can also write as torch.mul(tensor, 10)
print(tensor)

tensor([1, 2, 3])
tensor([10, 20, 30])


In [ ]:
#substraction
tensor = tensor - 10
tensor

tensor([ 0, 10, 20])

**Matrix Multiplication**

There are two types of multiplications in neural networks and deep learning

1.Element wise multiplication

2.Matrix Multiplication(dot product)

In [ ]:
tensor = torch.tensor([1, 2, 3])
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor* tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
#matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 944 µs, sys: 0 ns, total: 944 µs
Wall time: 896 µs


tensor(14)

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"shape is ",output.shape)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
shape is  torch.Size([3, 3])


In [ ]:
#To fix our tensor shape issues we can manipulate tensors using transpose
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

**Finding the min, max, mean, sum, etc(tensor aggregation)**

In [ ]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
#finding the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#finding the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#finding the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Finding the positional min and max

In [ ]:
#find the position in tensor that has min value => the index at which min value occurs
x.argmin()

tensor(0)

In [ ]:
#find the position of tensor that has max value => the index at which max value is present
x.argmax()

tensor(9)

**Reshaping, Stacking, Squeezing and Unsqueezing tensors**

Reshaping - reshapes the input tensor to defined shape

View - returns a view of an input tensor of certain shape but keep the same memory as the poriginal

Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

squeeze - removes all 'l' dimensions from a tensor

Unsqueeze - add a 'l' dimension to a target tensor

Permute - return a view of the input with dimensions permutted(swapped in a certain way)

In [ ]:
#Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
#change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z changes x(because a view of a tensor shares memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#torch.squeeze() - removes all single dimensions from a target tensor
x_squeezed = x_reshaped.squeeze()
print(f"squeezed tensor:", x_squeezed ),
print(f"squeezed tensor shape:", x_reshaped.squeeze().shape),

print(f"original tensor:", x_reshaped),
print(f"original tensor shape:", x_reshaped.shape)

squeezed tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
squeezed tensor shape: torch.Size([9])
original tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
original tensor shape: torch.Size([9, 1])


In [ ]:
#torch.unsqueeze() - adds a single dimension to the target tensor at specific dimension
print(f"previous target:", x_squeezed)
#Add an extra dimension usoing unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"new unsqueed tensor:", x_unsqueezed)
print(f"new unsqueezed tensor shape:", x_unsqueezed.shape)

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new unsqueed tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
new unsqueezed tensor shape: torch.Size([9, 1])


In [ ]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))
print(f"original tensor:",x_original)
#permute the original tensor to rearrange the axis(or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2 , 2->0
print(f"permuted tensor:", x_permuted)

original tensor: tensor([[[0.9044, 0.7812, 0.3206],
         [0.9784, 0.7111, 0.2434],
         [0.0186, 0.4555, 0.0490],
         ...,
         [0.8876, 0.3000, 0.9270],
         [0.9432, 0.0271, 0.8053],
         [0.4409, 0.7754, 0.1145]],

        [[0.9912, 0.3689, 0.9483],
         [0.5311, 0.0873, 0.0785],
         [0.1323, 0.6806, 0.9621],
         ...,
         [0.6959, 0.1186, 0.1185],
         [0.5151, 0.7933, 0.6888],
         [0.1835, 0.0647, 0.4881]],

        [[0.5048, 0.1050, 0.2488],
         [0.5387, 0.9737, 0.6301],
         [0.1824, 0.0625, 0.0331],
         ...,
         [0.2364, 0.9212, 0.2821],
         [0.1078, 0.8230, 0.4706],
         [0.9640, 0.6698, 0.5482]],

        ...,

        [[0.7046, 0.7611, 0.4602],
         [0.7198, 0.9269, 0.3760],
         [0.0045, 0.6209, 0.4096],
         ...,
         [0.9257, 0.8001, 0.2396],
         [0.1942, 0.2725, 0.8598],
         [0.3257, 0.1416, 0.4323]],

        [[0.1356, 0.1826, 0.9919],
         [0.6943, 0.6131, 0.39

**Indexing(Selecting data from tensors)**

indexing in pytorch is similar to indexing with Numpy

In [ ]:
#create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Let's index on the most inner bracket(last dimension)
x[0][0][0]

tensor(1)

In [ ]:
#Get all values of 0th and 1st dimensions but only index1 of 2nd dimension
print(x[:, :, 1])
print(x[:, 1, :])

tensor([[2, 5, 8]])
tensor([[4, 5, 6]])


**PyTorch tensors and numpy**

Numpy is popular scientific numerical computing library

PyTorch has functionality to interact with the numpy

->Data in Numpy, want in PyTorch Tensor-> torch.from_numpy(ndarray)

->PyTorch tensor->NuPy-> torch.Tensor.numpy()

In [ ]:
#Numpy Array to tensor
import torch
import numpy as np

array = np.arange(1.0 , 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

**Reproducbility(trying to take random out of random)**

In Short how neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them of data -> again -> again -> again ....

To reduce randomness in neural networks and PyTorch comes the concept of a random seed

Essentially what the random seed does is "flavour" the randomness

In [ ]:
import torch
#create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(f"random A tensor: ", random_tensor_A)
print(f"random B tensor: ", random_tensor_B)
print(random_tensor_A == random_tensor_B)

random A tensor:  tensor([[0.7409, 0.7779, 0.3817, 0.0681],
        [0.4670, 0.5094, 0.2784, 0.8459],
        [0.6512, 0.7808, 0.4627, 0.8655]])
random B tensor:  tensor([[0.7318, 0.1986, 0.2425, 0.5675],
        [0.2187, 0.6915, 0.5360, 0.4278],
        [0.8354, 0.5420, 0.0676, 0.0195]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Let's make random but reproducible tensors
import torch
#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


**Running tensors and PyTorch objects on the GPUs(and making faster computations)**



In [ ]:
#Running tensors and PyTorch objects on the GPUs
#Getting a GPU
#1.Easiest -use google colab
#2.Set up the GPUs by installing
#3.Use cloud computing
!nvidia-smi

Mon Feb 12 06:25:28 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P0              28W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
#Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
#Set Up device agonstic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count number of devices
torch.cuda.device_count()

1

**Putting tensors(and models) on the GPU**

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations


In [ ]:
#create a tensor(default on the cpu)
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#creating a tensor on GPU
#Move tensor to GPU(if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
#To fix the GPU tensor with Numpy issue, we can fisrt set into CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])