<a href="https://colab.research.google.com/github/Pradeep24032004/PyTorch-/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvdia-smi


/bin/bash: line 1: nvdia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [4]:
#Introduction to tensors
#creating tensors
#scalars
scalar = torch.tensor(7)
scalar


tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#get tensor as python int
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#Matrix
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX


tensor([[1, 2],
        [3, 4]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([3, 4])

In [13]:
MATRIX.shape

torch.Size([2, 2])

Generally in tensors scalars are represented by lower case letters like 'a', vectors are represented by lower case letters like 'y', matrix is represented by upper case letters like 'Q' and tenosrs are represented by upper case letters like 'X'

In [14]:
#Random Tensors
#random tensors are important because the way many neural networks learn is that they start with tensors full random numbers and then adjust the random numbers to better represent the data
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2636, 0.9187, 0.5929, 0.9858],
        [0.1429, 0.6632, 0.7748, 0.5338],
        [0.8693, 0.5536, 0.2319, 0.8206]])

In [15]:
#create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels(R, G, B)
random_image_tensor

tensor([[[1.1913e-01, 8.2397e-02, 4.1673e-01],
         [5.1530e-01, 7.6370e-02, 9.9667e-02],
         [8.3518e-01, 9.2562e-01, 9.6660e-01],
         ...,
         [5.4641e-01, 4.3162e-01, 8.0684e-01],
         [8.0473e-01, 7.3906e-02, 7.6357e-01],
         [5.2550e-01, 8.7290e-01, 5.4712e-01]],

        [[8.0896e-01, 9.3271e-01, 3.9666e-01],
         [2.4763e-02, 9.8138e-01, 5.2376e-01],
         [6.3389e-01, 8.8769e-01, 8.6765e-01],
         ...,
         [7.5171e-01, 4.7097e-01, 5.1364e-01],
         [3.1429e-01, 3.7843e-01, 9.7837e-01],
         [3.0347e-01, 1.4272e-01, 7.7283e-01]],

        [[8.8716e-01, 7.8700e-01, 5.9682e-02],
         [5.7415e-01, 9.1300e-01, 9.8919e-01],
         [7.7052e-01, 1.9912e-02, 5.6952e-01],
         ...,
         [5.8977e-02, 5.6671e-01, 8.3076e-01],
         [1.8905e-01, 1.2053e-01, 3.0529e-01],
         [8.1109e-01, 3.3386e-01, 8.0488e-02]],

        ...,

        [[5.0509e-01, 9.6564e-01, 9.2756e-01],
         [8.2073e-01, 6.8204e-01, 8.6029e-02]

In [16]:
random_image_tensor.ndim

3

***Zeros and Ones***

In [17]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
#creat6e tensor of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
#data type
ones.dtype

torch.float32

Creating a range of tensors and tensors-like


In [20]:
#use torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
one_to_ten = torch.arange(start=1, end = 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#creating tenors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
#Tensor datatypes
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 4.0, 7.0], dtype=None,#datatype whether float or int
                               device=None,  #running on which device cpu or gpu
                               requires_grad=False ) #to keep track of gradient descent or not
float_32_tensor

tensor([3., 4., 7.])

In [24]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 4., 7.], dtype=torch.float16)