<a href="https://colab.research.google.com/github/Pradeep24032004/PyTorch-/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvdia-smi


/bin/bash: line 1: nvdia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [3]:
#Introduction to tensors
#creating tensors
#scalars
scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#get tensor as python int
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7, 7])
vector


tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX


tensor([[1, 2],
        [3, 4]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([3, 4])

In [12]:
MATRIX.shape

torch.Size([2, 2])

Generally in tensors scalars are represented by lower case letters like 'a', vectors are represented by lower case letters like 'y', matrix is represented by upper case letters like 'Q' and tenosrs are represented by upper case letters like 'X'

In [13]:
#Random Tensors
#random tensors are important because the way many neural networks learn is that they start with tensors full random numbers and then adjust the random numbers to better represent the data
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5284, 0.5295, 0.4413, 0.4427],
        [0.8984, 0.1163, 0.9702, 0.1222],
        [0.0901, 0.1837, 0.4054, 0.6441]])

In [14]:
#create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels(R, G, B)
random_image_tensor

tensor([[[0.8321, 0.2707, 0.7564],
         [0.5091, 0.8193, 0.0775],
         [0.6066, 0.0578, 0.6359],
         ...,
         [0.9358, 0.6880, 0.2105],
         [0.6676, 0.0463, 0.1944],
         [0.5772, 0.5698, 0.5569]],

        [[0.3210, 0.3262, 0.4063],
         [0.0257, 0.0896, 0.4598],
         [0.2317, 0.8625, 0.6952],
         ...,
         [0.1758, 0.4723, 0.8539],
         [0.9471, 0.9903, 0.5223],
         [0.8325, 0.3302, 0.7556]],

        [[0.6149, 0.3671, 0.1179],
         [0.6989, 0.9174, 0.0380],
         [0.7227, 0.1194, 0.5524],
         ...,
         [0.9107, 0.1950, 0.1817],
         [0.9992, 0.9875, 0.0811],
         [0.4060, 0.8830, 0.1395]],

        ...,

        [[0.3009, 0.6165, 0.0494],
         [0.3526, 0.4172, 0.8435],
         [0.1900, 0.3937, 0.2050],
         ...,
         [0.1024, 0.0063, 0.0518],
         [0.3575, 0.2256, 0.0215],
         [0.8754, 0.5342, 0.1615]],

        [[0.6177, 0.1543, 0.9134],
         [0.7400, 0.8407, 0.7562],
         [0.

In [15]:
random_image_tensor.ndim

3

***Zeros and Ones***

In [16]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
#creat6e tensor of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
#data type
ones.dtype

torch.float32

Creating a range of tensors and tensors-like


In [19]:
#use torch.arange()
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
one_to_ten = torch.arange(start=1, end = 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
#creating tenors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
#Tensor datatypes
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 4.0, 7.0], dtype=None,#datatype whether float or int
                               device=None,  #running on which device cpu or gpu
                               requires_grad=False ) #to keep track of gradient descent or not
float_32_tensor

tensor([3., 4., 7.])

In [23]:
float_32_tensor.dtype

torch.float32

In [24]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 4., 7.], dtype=torch.float16)

In [25]:
float_16_tensor*float_32_tensor

tensor([ 9., 16., 49.])

In [26]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

**Getting information from tensors(tensor attributes)**
1. tenosr.dtype -gives info about data rype of tensor
2. tensor.shape - gives the shape of the tensor
3. tensor.device - gives info about on which device the code is running(cpu or gpu etc)

In [27]:
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Dtatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3358, 0.8784, 0.7571, 0.3957],
        [0.4129, 0.2673, 0.0233, 0.9665],
        [0.1378, 0.1416, 0.6652, 0.7239]])
Dtatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [28]:
#Manipulating tensors(Tensor operations)
#create a tensor and 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10 #can also write as torch.add(torch, 10)

tensor([11, 12, 13])

In [29]:
#multiply tensor by 10
tensor * 10
print(tensor)
#reasigning tensor
tensor = tensor * 10 #can also write as torch.mul(tensor, 10)
print(tensor)

tensor([1, 2, 3])
tensor([10, 20, 30])


In [30]:
#substraction
tensor = tensor - 10
tensor

tensor([ 0, 10, 20])

**Matrix Multiplication**

There are two types of multiplications in neural networks and deep learning

1.Element wise multiplication

2.Matrix Multiplication(dot product)

In [31]:
tensor = torch.tensor([1, 2, 3])
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor* tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [34]:
#matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 876 µs, sys: 6 µs, total: 882 µs
Wall time: 614 µs


tensor(14)

In [40]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"shape is ",output.shape)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
shape is  torch.Size([3, 3])


In [41]:
#To fix our tensor shape issues we can manipulate tensors using transpose
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

**Finding the min, max, mean, sum, etc(tensor aggregation)**

In [45]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [43]:
#finding the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [44]:
#finding the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [47]:
#finding the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [48]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Finding the positional min and max

In [49]:
#find the position in tensor that has min value => the index at which min value occurs
x.argmin()

tensor(0)

In [50]:
#find the position of tensor that has max value => the index at which max value is present
x.argmax()

tensor(9)

**Reshaping, Stacking, Squeezing and Unsqueezing tensors**

Reshaping - reshapes the input tensor to defined shape

View - returns a view of an input tensor of certain shape but keep the same memory as the poriginal

Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)

squeeze - removes all 'l' dimensions from a tensor

Unsqueeze - add a 'l' dimension to a target tensor

Permute - return a view of the input with dimensions permutted(swapped in a certain way)

In [68]:
#Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [69]:
#Add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [70]:
#change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
#changing z changes x(because a view of a tensor shares memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [74]:
#stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [79]:
#torch.squeeze() - removes all single dimensions from a target tensor
x_squeezed = x_reshaped.squeeze()
print(f"squeezed tensor:", x_squeezed ),
print(f"squeezed tensor shape:", x_reshaped.squeeze().shape),

print(f"original tensor:", x_reshaped),
print(f"original tensor shape:", x_reshaped.shape)

squeezed tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
squeezed tensor shape: torch.Size([9])
original tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
original tensor shape: torch.Size([9, 1])


In [82]:
#torch.unsqueeze() - adds a single dimension to the target tensor at specific dimension
print(f"previous target:", x_squeezed)
#Add an extra dimension usoing unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"new unsqueed tensor:", x_unsqueezed)
print(f"new unsqueezed tensor shape:", x_unsqueezed.shape)

previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new unsqueed tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
new unsqueezed tensor shape: torch.Size([9, 1])


In [87]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3))
print(f"original tensor:",x_original)
#permute the original tensor to rearrange the axis(or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2 , 2->0
print(f"permuted tensor:", x_permuted)

original tensor: tensor([[[0.4098, 0.7334, 0.2085],
         [0.8376, 0.9947, 0.3669],
         [0.4836, 0.9995, 0.0976],
         ...,
         [0.4480, 0.7996, 0.1486],
         [0.4528, 0.3855, 0.8218],
         [0.9267, 0.8683, 0.9224]],

        [[0.4749, 0.5371, 0.6205],
         [0.7495, 0.7912, 0.6854],
         [0.2140, 0.3320, 0.6356],
         ...,
         [0.6473, 0.5054, 0.5122],
         [0.7987, 0.3949, 0.0569],
         [0.9915, 0.8578, 0.1014]],

        [[0.7838, 0.6249, 0.4683],
         [0.0366, 0.5312, 0.7485],
         [0.9436, 0.6762, 0.3722],
         ...,
         [0.8697, 0.4975, 0.3315],
         [0.0295, 0.1769, 0.4845],
         [0.1388, 0.0142, 0.7285]],

        ...,

        [[0.7813, 0.6584, 0.3074],
         [0.2979, 0.5185, 0.7165],
         [0.9715, 0.9480, 0.1920],
         ...,
         [0.9414, 0.0715, 0.5409],
         [0.6520, 0.5767, 0.0433],
         [0.4037, 0.7687, 0.5351]],

        [[0.9553, 0.0216, 0.8644],
         [0.0077, 0.8632, 0.29